#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend sage-frontend
        bind *:80
        mode http
        default_backend sage-backend

backend sage-backend
        balance roundrobin
        server 131064-web-01 54.175.166.7:80 check
        server 131064-web-02 18.204.16.81:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
